# Generated by Django 4.2.5 on 2023-11-19 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitorder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_price', models.FloatField(default=0.0)),
                ('limit_price', models.FloatField(default=0.0)),
                ('crossed', models.PositiveIntegerField(default=0)),
                ('cross_count', models.PositiveIntegerField(default=0)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='initiated', max_length=12)),
                ('syntax', models.CharField(default='', max_length=1000)),
            ],
            options={
                'verbose_name': 'Limit Order',
                'verbose_name_plural': 'Limit Orders',
            },
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('headline', models.TextField(default='', max_length='1000', null=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='ordertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segment',
            },
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stg', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategy',
            },
        ),
        migrations.CreateModel(
            name='trailing_stoploss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('stoploss', models.FloatField(default=0.0)),
                ('target', models.FloatField(default=0.0)),
                ('ordered_price', models.FloatField(default=0.0)),
                ('exit_avg', models.FloatField(default=0.0)),
                ('current_price', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(default='BUY', max_length=5)),
                ('symbol', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='initiated', max_length=12)),
                ('message', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Trailing alert',
                'verbose_name_plural': 'Trailing Alerts',
            },
        ),
        migrations.CreateModel(
            name='webhookurl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(default='98010bd9270f9b100b6214a21754fd33bdc8d41b2bc9f9dd16ff54d3c34ffd71', max_length=500)),
                ('tag', models.CharField(choices=[('webhook', 'webhook'), ('smartorder', 'smartorder')], default='webhook', max_length=50)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Url',
                'verbose_name_plural': 'Webhooks',
            },
        ),
        migrations.CreateModel(
            name='tradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiid', models.CharField(default='', max_length=500)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('response', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='', max_length=500)),
                ('broker', models.CharField(default='', max_length=500)),
                ('quantity', models.CharField(default='0', max_length=500)),
                ('symbol', models.CharField(default='s', max_length=500)),
                ('buy', models.CharField(default='0', max_length=500)),
                ('p_l', models.FloatField(default=0.0)),
                ('sell', models.CharField(default='0', max_length=500)),
                ('apiuser', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responses',
                'verbose_name_plural': 'Responses',
            },
        ),
        migrations.CreateModel(
            name='paisaapi',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('apiname', models.CharField(default='xyz', max_length=100)),
                ('appsource', models.CharField(default='source', max_length=100)),
                ('userid', models.CharField(default='xyz', max_length=100)),
                ('password', models.CharField(default='xyz', max_length=100)),
                ('userkey', models.CharField(default='xxxxxxxxxxxx', max_length=100)),
                ('encryptionkey', models.CharField(default='xxxxxxxxxxxx', max_length=100)),
                ('secretkey', models.CharField(default='secretkey', max_length=500)),
                ('clientcode', models.CharField(default='clientcode', max_length=500)),
                ('mpin', models.CharField(default='123456', max_length=500)),
                ('is_trading', models.BooleanField(default=False)),
                ('apiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5Paisa API',
                'verbose_name_plural': '5Paisa API',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_time', models.DateField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='fyersapi',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('apiname', models.CharField(default='xyz', max_length=100)),
                ('clientid', models.CharField(default='xyz', max_length=100)),
                ('secretkey', models.CharField(default='xxxxxxxxxxxx', max_length=100)),
                ('authcode', models.CharField(default='xxxxxxxxxxxx', max_length=1000)),
                ('accesstoken', models.CharField(default='xxxxxxxxxxxx', max_length=1000)),
                ('is_trading', models.BooleanField(default=False)),
                ('apiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fyers API',
                'verbose_name_plural': 'Fyers API',
            },
        ),
        migrations.CreateModel(
            name='dhanapi',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('apiname', models.CharField(default='xyz', max_length=100)),
                ('clientid', models.CharField(default='xyz', max_length=100)),
                ('accesstoken', models.CharField(default='xxxxxxxxxxxx', max_length=1000)),
                ('is_trading', models.BooleanField(default=False)),
                ('apiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dhan API',
                'verbose_name_plural': 'Dhan API',
            },
        ),
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('contactid', models.AutoField(primary_key=True, serialize=False)),
                ('numemail', models.CharField(default='', max_length=100)),
                ('issue', models.CharField(default='', max_length=5000)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='bot_order_quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('crudeoil_quantity', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('nifty_quantity', models.PositiveIntegerField(blank=True, default=50, null=True)),
                ('bank_nifty_quantity', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('fin_nifty_quantity', models.PositiveIntegerField(blank=True, default=40, null=True)),
                ('sensex_quantity', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quantity Setting',
                'verbose_name_plural': 'Quantity Setting',
            },
        ),
        migrations.CreateModel(
            name='angelapi',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('apiname', models.CharField(default='xyz', max_length=100)),
                ('clientid', models.CharField(default='xyz', max_length=100)),
                ('password', models.CharField(default='xyz', max_length=100)),
                ('apikey', models.CharField(default='xxxxxxxxxxxx', max_length=100)),
                ('totp', models.CharField(default='1234', max_length=100)),
                ('rtoken', models.CharField(default='refreshtoken', max_length=500)),
                ('authtoken', models.CharField(default='authtoken', max_length=2000)),
                ('is_trading', models.BooleanField(default=False)),
                ('apiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Angel API',
                'verbose_name_plural': 'Angel API',
            },
        ),
        migrations.CreateModel(
            name='allstratergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.CharField(default='0', max_length=100)),
                ('symbol', models.CharField(default='', max_length=100)),
                ('broker', models.CharField(choices=[('None', 'None'), ('Fyers', 'Fyers'), ('Angel ONE', 'Angel ONE'), ('Alice Blue', 'Alice Blue'), ('Dhan HQ', 'Dhan HQ'), ('5 Paisa', '5 Paisa')], default='None', max_length=50)),
                ('apiid', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('order_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trade.ordertype')),
                ('product_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trade.producttype')),
                ('segment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trade.segment')),
                ('strategy', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trade.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All Strategy',
                'verbose_name_plural': 'All Strategy',
            },
        ),
        migrations.CreateModel(
            name='allplan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suscribed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('plan_type', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic -> 1500'), ('Pro', 'Pro -> 2500'), ('VIP', 'VIP -> 3500'), ('Premium', 'Premium -> 4500')], default='Expire', max_length=50)),
                ('order_id', models.CharField(default='', max_length=255)),
                ('checksum', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('placed_order', models.PositiveIntegerField(default=0, null=True)),
                ('totalorder_perday', models.CharField(default='10', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='aliceapi',
            fields=[
                ('apiid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('apiname', models.CharField(default='xyz', max_length=100)),
                ('userid', models.CharField(default='xyz', max_length=100)),
                ('apikey', models.CharField(default='xxxxxxxxxxxx', max_length=500)),
                ('is_trading', models.BooleanField(default=False)),
                ('apiuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alice API',
                'verbose_name_plural': 'Alice API',
            },
        ),
    ]
