# Generated by Django 4.2.5 on 2023-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='webhookurl',
        ),
    ]
