# Generated by Django 4.2.5 on 2023-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_delete_webhookurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='webhookurl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(default='98010bd9270f9b100b6214a21754fd33bdc8d41b2bc9f9dd16ff54d3c34ffd71', max_length=500)),
                ('use', models.CharField(choices=[('webhook', 'webhook'), ('smartorder', 'smartorder')], default='webhook', max_length=50)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook Url',
                'verbose_name_plural': 'Webhooks',
            },
        ),
    ]
