# Generated by Django 4.2.5 on 2023-11-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_webhookurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookurl',
            name='slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhookurl',
            name='use',
            field=models.CharField(choices=[('webhook', 'webhook'), ('smartorder', 'smartorder'), ('time_slot', 'time_slot')], default='webhook', max_length=50),
        ),
    ]
