# Generated by Django 4.2.5 on 2023-11-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_webhookurl_slot_alter_webhookurl_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookurl',
            name='url',
            field=models.CharField(default='webhook', max_length=500),
        ),
    ]
