# Generated by Django 4.2.5 on 2023-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_webhookurl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorder',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='initiated', max_length=12),
        ),
        migrations.AlterField(
            model_name='trailing_stoploss',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='initiated', max_length=12),
        ),
    ]
