# Generated by Django 4.2.8 on 2024-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_limitorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic -> 1500'), ('Pro', 'Pro -> 2500'), ('VIP', 'VIP -> 3500'), ('Premium', 'Premium -> 4500')], default='Expire', max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('after_discount_price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan Settings',
                'verbose_name_plural': 'Plan Settings',
            },
        ),
    ]
