# Generated by Django 4.2.8 on 2024-02-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=80)),
                ('content', models.TextField()),
                ('iframe', models.CharField(default='', max_length=200)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
