# Generated by Django 4.2.5 on 2024-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_tradehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tradehistory',
            unique_together={('date_time', 'symbol', 'client_id')},
        ),
    ]
