# Generated by Django 4.2.5 on 2024-04-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_tradehistory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='date_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
