# Generated by Django 4.2.5 on 2024-04-30 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0012_alter_tradehistory_date_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tradehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='broker',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tradehistory',
            unique_together={('date_time', 'symbol', 'client_id', 'broker', 'user')},
        ),
    ]
