# Generated by Django 4.2.5 on 2023-12-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executed_Stratergy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('remark', models.CharField(max_length=100)),
                ('syntax_used', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name': 'Executed Orders',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('url', models.CharField(max_length=150)),
                ('upstox_access_token', models.CharField(default='', max_length=5000)),
                ('stratergy', models.CharField(choices=[('Manual Input', 'Manual Input')], default='', max_length=50)),
                ('symbol', models.CharField(default='Same as present in Onstock', max_length=50)),
                ('buy_syntax', models.TextField()),
                ('sell_syntax', models.TextField()),
                ('high', models.PositiveIntegerField(default=0)),
                ('low', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('run_till', models.PositiveIntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
