# Generated by Django 4.2.5 on 2023-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='run_till',
        ),
        migrations.AddField(
            model_name='alert',
            name='function',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='gap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='gap_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='last_volume',
            field=models.PositiveIntegerField(default=5000000000000),
        ),
        migrations.AddField(
            model_name='alert',
            name='ltp',
            field=models.PositiveIntegerField(default=5000000000000),
        ),
        migrations.AddField(
            model_name='alert',
            name='position_status',
            field=models.CharField(choices=[('EMPTY', 'EMPTY'), ('POSITION_OPEN', '_POSITION_OPEN'), ('SCALP_POSITION_OPEN', 'SCALP_POSITION_OPEN'), ('POSITION_CLOSED', 'POSITION_CLOSED'), ('SCALP_POSITION_CLOSED', 'SCALP_POSITION_CLOSED')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='segment',
            field=models.CharField(default='Same as present in Onstock', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
