# Generated by Django 4.2.5 on 2023-12-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0002_remove_alert_run_till_alert_function_alert_gap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='gap_completed',
        ),
    ]
