# Generated by Django 4.2.5 on 2023-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0003_remove_alert_gap_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='ltp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='position_status',
            field=models.CharField(choices=[('EMPTY', 'EMPTY'), ('POSITION_OPEN', 'POSITION_OPEN'), ('SCALP_POSITION_OPEN', 'SCALP_POSITION_OPEN'), ('POSITION_CLOSED', 'POSITION_CLOSED'), ('SCALP_POSITION_CLOSED', 'SCALP_POSITION_CLOSED')], default='', max_length=50),
        ),
    ]
