# Generated by Django 4.2.8 on 2023-12-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0004_alter_alert_ltp_alter_alert_position_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='token',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='segment',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
