# Generated by Django 4.2.8 on 2024-01-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0005_alert_token_alter_alert_segment_alter_alert_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dhan_token',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='instrument_type',
            field=models.CharField(choices=[('EQUITY', 'EQUITY'), ('FUTCOM', 'FUTCOM'), ('INDEX', 'INDEX')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='segment',
            field=models.CharField(choices=[('NSE_EQ', 'NSE_EQ'), ('NSE_FNO', 'NSE_FNO'), ('IDX_I', 'IDX_I'), ('BSE_EQ', 'BSE_EQ'), ('MCX_COMM', 'MCX_COMM')], default='', max_length=50),
        ),
    ]
