# Generated by Django 4.2.8 on 2024-01-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0006_alert_dhan_token_alert_instrument_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='instrument_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='segment',
            field=models.CharField(default='', max_length=50),
        ),
    ]
