# Generated by Django 4.2.8 on 2024-01-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0008_alter_alert_instrument_type_alter_alert_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='instrument_type',
            field=models.CharField(choices=[('EQUITY', 'EQUITY'), ('FUTCOM', 'FUTCOM'), ('INDEX', 'INDEX'), ('FUTIDX', 'FUTIDX')], default='', max_length=50),
        ),
    ]
