# Generated by Django 4.2.8 on 2024-01-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0009_alter_alert_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='executed_stratergy',
            name='url',
            field=models.CharField(default='https://smart-algo.in/alert/smartorder', max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(default='-----', max_length=50),
        ),
        migrations.AlterField(
            model_name='executed_stratergy',
            name='response',
            field=models.CharField(max_length=100),
        ),
    ]
