# Generated by Django 4.2.8 on 2024-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0011_stratergy_settings_remove_alert_dhan_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratergy_settings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
