# Generated by Django 4.2.8 on 2024-01-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0012_stratergy_settings_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stratergy_settings',
            options={'verbose_name': 'Stratergy Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='stratergy_settings',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stratergy_settings',
            name='upstox_access_token',
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='access_token',
            field=models.CharField(default='Leave it blank', max_length=1000),
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='api_key',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='code',
            field=models.CharField(default='Leave it blank', max_length=100),
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='redirect_uri',
            field=models.CharField(default='https://smart-algo.in/upstox_cred', max_length=120),
        ),
        migrations.AddField(
            model_name='stratergy_settings',
            name='secret_key',
            field=models.CharField(default='', max_length=300),
        ),
    ]
