# Generated by Django 4.2.8 on 2024-01-05 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0013_alter_stratergy_settings_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executed_stratergy',
            name='id',
        ),
        migrations.AlterField(
            model_name='executed_stratergy',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
