# Generated by Django 4.2.8 on 2024-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0014_remove_executed_stratergy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='symbol_name',
            field=models.CharField(default='-----', max_length=50),
        ),
    ]
