# Generated by Django 4.2.8 on 2024-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0015_alert_symbol_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
