# Generated by Django 4.2.8 on 2024-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0016_alert_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='gap',
            field=models.IntegerField(default=0),
        ),
    ]
