# Generated by Django 4.2.8 on 2024-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0017_alter_alert_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
