# Generated by Django 4.2.8 on 2024-03-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0020_dhan_settings_stratergyalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratergyalert',
            name='current_volume',
        ),
        migrations.RemoveField(
            model_name='stratergyalert',
            name='last_volume',
        ),
        migrations.RemoveField(
            model_name='stratergyalert',
            name='symbol_name',
        ),
        migrations.AddField(
            model_name='stratergyalert',
            name='ask_Qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stratergyalert',
            name='bid_Qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
