# Generated by Django 4.2.7 on 2024-03-18 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0024_alter_executed_stratergy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executed_stratergy',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 14, 2, 7, 106151, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
        ),
    ]
