# Generated by Django 4.2.8 on 2024-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0025_alter_executed_stratergy_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executed_stratergy',
            name='datetime',
        ),
        migrations.AddField(
            model_name='executed_stratergy',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
