# Generated by Django 4.2.8 on 2024-03-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0026_remove_executed_stratergy_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executed_stratergy',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 19, 58, 2, 850712), null=True),
        ),
    ]
