# Generated by Django 4.2.7 on 2024-03-18 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stratergy', '0027_executed_stratergy_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executed_stratergy',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
