# Generated by Django 4.2.5 on 2023-11-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0005_alter_webhookurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('syntax', models.TextField()),
                ('status', models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='initiated', max_length=12)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.webhookurl')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
