# Generated by Django 4.2.5 on 2023-11-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date_time',
            new_name='datetime',
        ),
    ]
