# Generated by Django 4.2.5 on 2023-11-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_rename_date_time_orders_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('initiated', 'initiated'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed'), ('cancelled', 'cancelled')], default='initiated', max_length=12),
        ),
    ]
