# Generated by Django 4.2.8 on 2024-02-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_indextokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextokens',
            name='BANKEX',
            field=models.CharField(default='100', max_length=100),
        ),
        migrations.AddField(
            model_name='indextokens',
            name='FIN_NIFTY',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
